### ISSUE TITLE
Cannot import the trax library even when it is installed

### ISSUE THREAD

**Issue by mokshasoft** [google/trax#1363]
### Description

Cannot import the trax package even when it is installed.

### Environment information
I do not have pip, but the pip3 command installed via homebrew.

```
OS:  macOS 10.15.7 (19H114)

$ pip freeze | grep trax
trax==1.2.4

$ pip freeze | grep tensor
mesh-tensorflow==0.1.18
tensor2tensor==1.15.4
tensorflow-datasets==4.2.0
tensorflow-gan==2.0.0
tensorflow-hub==0.11.0
tensorflow-metadata==0.26.0
tensorflow-probability==0.7.0

$ pip freeze | grep jax
jax==0.2.8
jaxlib==0.1.57

$ python -V
Python 2.7.16

$ python3 -V
Python 3.9.1
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:
% cat test.py 
#!/usr/bin/env python3
import trax

Running
% ./test.py 
```

# Error logs:
```
Traceback (most recent call last):
  File "/Users/clajo/Repos/OpenSource/ML/./test.py", line 3, in <module>
    import trax
  File "/Users/clajo/Repos/OpenSource/ML/trax.py", line 3, in <module>
    from trax.fastmath import numpy as fastnp
ModuleNotFoundError: No module named 'trax.fastmath'; 'trax' is not a package
```

**Comment by zack466** [comment]
Looking at the stack trace, it appears there is a file in the same directory as `test.py` with the filename `trax.py`. This name conflicts with the actual trax package, which is probably why it's giving you an error.

**Comment by mokshasoft** [comment]
Thank you! That solved the problem.
