### ISSUE TITLE
training.Loop() fails to load a (self-)pickled model

### ISSUE THREAD

**Issue by sedelnik** [google/trax#1433]
### Description

training.Loop() fails to load a pickled model when I execute a GRU training code from Coursera's NLP course on my local machine (https://www.coursera.org/learn/sequence-models-in-nlp/programming/RWKwg/lab)

Apparently the model is pickled during the training process (there's no code that explicitly pickles it)

I provide an error log below, would be glad to get a hint on how to resolve this issue  

### Environment information
OS: <ubuntu 18.04>

$ pip freeze | grep trax
trax==1.3.7

$ pip freeze | grep tensor
mesh-tensorflow==0.1.18
tensorboard==2.4.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.4.1
tensorflow-datasets==4.2.0
tensorflow-estimator==2.4.0
tensorflow-hub==0.11.0
tensorflow-metadata==0.27.0
tensorflow-text==2.4.3

$ pip freeze | grep jax
jax==0.2.9
jaxlib==0.1.59+cuda110

$ python -V
python -V

### For bugs: reproduction and error logs

# Steps to reproduce:
Execute the code from https://www.coursera.org/learn/sequence-models-in-nlp/programming/RWKwg/lab, with minor corrections (replacing eval_task=eval_task with eval_tasks=[eval_task,])

# Error logs:
Traceback (most recent call last):
  File "/home/ilya/PycharmProjects/TraxGRU/main.py", line 402, in <module>
    main()
  File "/home/ilya/PycharmProjects/TraxGRU/main.py", line 383, in main
    training_loop = train_model(GRULM(), data_generator,lines=lines,eval_lines=eval_lines)
  File "/home/ilya/PycharmProjects/TraxGRU/main.py", line 224, in train_model
    random_seed=32)
  File "/home/ilya/anaconda3/lib/python3.7/site-packages/trax/supervised/training.py", line 234, in __init__
    self.load_checkpoint()
  File "/home/ilya/anaconda3/lib/python3.7/site-packages/trax/supervised/training.py", line 805, in load_checkpoint
    d['flat_weights'], d['flat_state'], weights_and_state_sig)
  File "/home/ilya/anaconda3/lib/python3.7/site-packages/trax/layers/base.py", line 747, in unflatten_weights_and_state
    copy_from_tree=weights_to_copy)
  File "/home/ilya/anaconda3/lib/python3.7/site-packages/trax/fastmath/numpy.py", line 243, in tree_unflatten
    new_t, rest = tree_unflatten(rest, t, copy_from_tree=copy_from_tree)
  File "/home/ilya/anaconda3/lib/python3.7/site-packages/trax/fastmath/numpy.py", line 243, in tree_unflatten
    new_t, rest = tree_unflatten(rest, t, copy_from_tree=copy_from_tree)
  File "/home/ilya/anaconda3/lib/python3.7/site-packages/trax/fastmath/numpy.py", line 243, in tree_unflatten
    new_t, rest = tree_unflatten(rest, t, copy_from_tree=copy_from_tree)
  [Previous line repeated 1 more time]
  File "/home/ilya/anaconda3/lib/python3.7/site-packages/trax/fastmath/numpy.py", line 253, in tree_unflatten
    return flat[0], flat[1:]
IndexError: list index out of range

**Comment by alanyeung95** [comment]
@sedelnik how did you solve it? As I come across the same issue and error. And I really need some help. Thank you.

**Comment by sedelnik** [comment]
I reverted to earlier version of Trax, not quite a "solution", but it was
good enough for me.

If you find a real solution, let me know.

Best regards,
Ilya

**Comment by alanyeung95** [comment]
Thank you for your quick response @sedelnik , I will try it myself. 

Many thanks.
