### ISSUE TITLE
Does Trax depend on Cuda and Tensorflow? 

### ISSUE THREAD

**Issue by Marry-20** [google/trax#1572]
Do we need to install Trax on Nvidia? 
**When I run "import Trax" on the computer "intel", I receive this error:** 

W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/mahya/NLP_trax/Natural-Language-Processing-Specialization/Natural Language Processing with Attention Models/Week 4/test_py/C4_W4_Assignment_Solution.py", line 44, in <module>
    import trax
  File "/usr/local/lib/python3.9/site-packages/trax/__init__.py", line 18, in <module>
    from trax import layers
  File "/usr/local/lib/python3.9/site-packages/trax/layers/__init__.py", line 23, in <module>
    from trax.layers.activation_fns import *
  File "/usr/local/lib/python3.9/site-packages/trax/layers/activation_fns.py", line 26, in <module>
    from trax import math
  File "/usr/local/lib/python3.9/site-packages/trax/math/__init__.py", line 18, in <module>
    from trax.math import jax as jax_math
  File "/usr/local/lib/python3.9/site-packages/trax/math/jax.py", line 28, in <module>
    import tensorflow_datasets as tfds
  File "/usr/local/lib/python3.9/site-packages/tensorflow_datasets/__init__.py", line 51, in <module>
    from tensorflow_datasets import __init__py3 as api
  File "/usr/local/lib/python3.9/site-packages/tensorflow_datasets/__init__py3.py", line 43, in <module>
    from tensorflow_datasets.core import tf_compat
  File "/usr/local/lib/python3.9/site-packages/tensorflow_datasets/core/__init__.py", line 25, in <module>
    from tensorflow_datasets.core import community  # pylint: disable=g-bad-import-order
  File "/usr/local/lib/python3.9/site-packages/tensorflow_datasets/core/community/__init__.py", line 18, in <module>
    from tensorflow_datasets.core.community.load import builder_cls_from_module
  File "/usr/local/lib/python3.9/site-packages/tensorflow_datasets/core/community/load.py", line 22, in <module>
    from tensorflow_datasets.core import dataset_builder
  File "/usr/local/lib/python3.9/site-packages/tensorflow_datasets/core/dataset_builder.py", line 32, in <module>
    from tensorflow_datasets.core import dataset_info
  File "/usr/local/lib/python3.9/site-packages/tensorflow_datasets/core/dataset_info.py", line 47, in <module>
    from tensorflow_datasets.core.features import feature as feature_lib
  File "/usr/local/lib/python3.9/site-packages/tensorflow_datasets/core/features/__init__.py", line 33, in <module>
    from tensorflow_datasets.core.features.text_feature import Text
  File "/usr/local/lib/python3.9/site-packages/tensorflow_datasets/core/features/text_feature.py", line 27, in <module>
    from tensorflow_datasets.core.deprecated import text as text_lib
  File "/usr/local/lib/python3.9/site-packages/tensorflow_datasets/core/deprecated/__init__.py", line 19, in <module>
    from tensorflow_datasets.core.download.checksums import add_checksums_dir
  File "/usr/local/lib/python3.9/site-packages/tensorflow_datasets/core/download/__init__.py", line 19, in <module>
    from tensorflow_datasets.core.download.download_manager import DownloadConfig
  File "/usr/local/lib/python3.9/site-packages/tensorflow_datasets/core/download/download_manager.py", line 32, in <module>
    from tensorflow_datasets.core.download import extractor
  File "/usr/local/lib/python3.9/site-packages/tensorflow_datasets/core/download/extractor.py", line 18, in <module>
    import bz2
  File "/usr/local/lib/python3.9/bz2.py", line 18, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
...

### Environment information
Python version: 3.8 and 3.9
Graphic: AMD® Turks / Intel® HD Graphics 3000 (SNB GT2)
ubuntu version:  20.04

```

**Comment by afrozenator** [comment]
`pip install trax` should install trax and its dependencies, let us know if that fails for you.

**Comment by bobbyhaliwela** [comment]
> > `pip install trax` should install trax and its dependencies, let us know if that fails for you.
> 
> Hi. I am using a completely new virtual machine with Ubuntu 20.04.2 LTS. When I try `pip install trax`. I got a bunch of compatibility errors. Plus, when I try to import trax, I got this error:
> `2021-08-11 18:54:19.836984: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory`

Got the same error today, while it was running fine just a month ago. Trying a solution a found on the internet to see if its working. Will edit this post if it does.
