### ISSUE TITLE
[Bug] import trax fails with "ImportError: cannot import name 'HistogramProto'"

### ISSUE THREAD

**Issue by vkataev** [google/trax#176]
### Description
Fails on import trax

### Environment information
Singularity image bootstrapped from "docker ubuntu:latest"

OS: Ubuntu 18.04 LTS

$ pip freeze | grep tensor
mesh-tensorflow==0.1.7
tensor2tensor==1.15.2
tensorboard==2.0.2
tensorflow==2.0.0
tensorflow-datasets==1.3.2
tensorflow-estimator==2.0.1
tensorflow-gan==2.0.0
tensorflow-hub==0.7.0
tensorflow-metadata==0.15.1
tensorflow-probability==0.7.0

$ pip freeze | grep jax
jax==0.1.55
jaxlib==0.1.37

$ python -V
Python 3.6.9

# Steps to reproduce:
python3 -c 'import trax'

# Error logs:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/venv/lib/python3.6/site-packages/trax/__init__.py", line 21, in <module>
    from trax import learning_rate as lr
  File "/venv/lib/python3.6/site-packages/trax/learning_rate.py", line 294, in <module>
    from trax.rl import online_tune
  File "/venv/lib/python3.6/site-packages/trax/rl/__init__.py", line 24, in <module>
    from trax.rl import simulated_env_problem
  File "/venv/lib/python3.6/site-packages/trax/rl/simulated_env_problem.py", line 29, in <module>
    from trax import trainer_lib
  File "/venv/lib/python3.6/site-packages/trax/trainer_lib.py", line 41, in <module>
    from trax import jaxboard
  File "/venv/lib/python3.6/site-packages/trax/jaxboard.py", line 38, in <module>
    from tensorflow import HistogramProto
ImportError: cannot import name 'HistogramProto'

**Comment by vkataev** [comment]
Found, the latest version on  pypi.org is 1.1.2 which is not TF-2 aware yet. So, one need to build a trax wheel to get latest master.
