### ISSUE TITLE
Reformer Encoder/Decoder is allergic to different lengths in source and target

### ISSUE THREAD

**Issue by tomweingarten** [google/trax#549]
When running the Reformer encoder/decoder model (not ReformerLM), an error is thrown if the source and target input are not identical lengths. If this is the intended behavior it is non-obvious to me. The analogous Transformer model works just fine with the same input. If I pad the lengths to be equal the model works great, but the memory usage is impractical for my problem. Thanks!

...

### Environment information

```
OS: Ubuntu 20.04

$ pip freeze | grep tensor
mesh-tensorflow==0.1.13
tensor2tensor==1.15.5
tensorboard==2.2.1
tensorboard-plugin-wit==1.6.0.post3
tensorflow-datasets==3.1.0
tensorflow-estimator==2.2.0
tensorflow-gan==2.0.0
tensorflow-gpu==2.2.0rc4
tensorflow-hub==0.8.0
tensorflow-metadata==0.21.2
tensorflow-probability==0.7.0

$ pip freeze | grep jax
jax==0.1.65
jaxlib==0.1.45

$ python -V
Python 3.8.2
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:

```
# Model defined as:
def reformer_lm(mode):
    return trax.models.Reformer(
        10000,
        output_vocab_size=10000,
        d_model=256,
        d_ff=1024,
        n_encoder_layers=16,
        n_decoder_layers=16,
        n_heads=4,
        dropout=0.1,
        mode=mode,
        max_len=6000
        )
```
# Error logs:

Traceback (most recent call last):
  File "tf_nfl_reformer.py", line 125, in <module>
    trainer = trax.supervised.Trainer(
  File "/home/tom/.local/lib/python3.8/site-packages/trax/supervised/trainer_lib.py", line 154, in __init__
    m_weights, m_state = metrics_in_parallel.init(output_signature)
  File "/home/tom/.local/lib/python3.8/site-packages/trax/layers/base.py", line 322, in init
    raise LayerError(name, 'init', self._caller,
trax.layers.base.LayerError: Exception passing through layer Branch (in init):
  layer created in file [...]/trax/layers/combinators.py, line 472
  layer input shapes: (ShapeDtype{shape:(1, 200, 7848), dtype:float32}, ShapeDtype{shape:(1, 3000), dtype:int32}, ShapeDtype{shape:(1, 3000), dtype:float32})

  File [...]/trax/layers/combinators.py, line 91, in new_weights_and_state
    weights_or_empty, state = sublayer.init(inputs)

LayerError: Exception passing through layer Parallel (in init):
  layer created in file [...]/trax/layers/combinators.py, line 470
  layer input shapes: (ShapeDtype{shape:(1, 200, 7848), dtype:float32}, ShapeDtype{shape:(1, 3000), dtype:int32}, ShapeDtype{shape:(1, 3000), dtype:float32}, ShapeDtype{shape:(1, 200, 7848), dtype:float32}, ShapeDtype{shape:(1, 3000), dtype:int32}, ShapeDtype{shape:(1, 3000), dtype:float32}, ShapeDtype{shape:(1, 200, 7848), dtype:float32}, ShapeDtype{shape:(1, 3000), dtype:int32}, ShapeDtype{shape:(1, 3000), dtype:float32}, ShapeDtype{shape:(1, 200, 7848), dtype:float32}, ShapeDtype{shape:(1, 3000), dtype:int32}, ShapeDtype{shape:(1, 3000), dtype:float32}, ShapeDtype{shape:(1, 200, 7848), dtype:float32}, ShapeDtype{shape:(1, 3000), dtype:int32}, ShapeDtype{shape:(1, 3000), dtype:float32})

  File [...]/trax/layers/combinators.py, line 250, in new_weights_and_state
    inits = [layer.init(signature)

  File [...]/trax/layers/combinators.py, line 250, in <listcomp>
    inits = [layer.init(signature)

LayerError: Exception passing through layer Serial (in init):
  layer created in file [...]/trax/layers/metrics.py, line 145
  layer input shapes: (ShapeDtype{shape:(1, 200, 7848), dtype:float32}, ShapeDtype{shape:(1, 3000), dtype:int32}, ShapeDtype{shape:(1, 3000), dtype:float32})

  File [...]/trax/layers/combinators.py, line 92, in new_weights_and_state
    outputs, _ = sublayer._forward_abstract(inputs)

LayerError: Exception passing through layer _Accuracy (in _forward_abstract):
  layer created in file [...]/trax/layers/metrics.py, line 63
  layer input shapes: (ShapeDtype{shape:(1, 200, 7848), dtype:float32}, ShapeDtype{shape:(1, 3000), dtype:int32})

  File [...]/trax/math/jax.py, line 175, in shape_fun
    jax_shapes = jax.eval_shape(f, *args, **kwargs)

  File [...]/site-packages/jax/api.py, line 1661, in eval_shape
    out = pe.abstract_eval_fun(wrapped_fun.call_wrapped,

  File [...]/jax/interpreters/partial_eval.py, line 340, in abstract_eval_fun
    _, pvals_out, _ = trace_to_jaxpr(lu.wrap_init(fun, params), pvals_in,

  File [...]/jax/interpreters/partial_eval.py, line 437, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)

  File [...]/site-packages/jax/linear_util.py, line 150, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))

  File [...]/site-packages/jax/linear_util.py, line 150, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))

  File [...]/trax/layers/base.py, line 479, in call_on_input
    return self.forward_with_state(x, weights=weights, state=state, rng=rng)

  File [...]/trax/layers/base.py, line 222, in forward_with_state
    return self.forward(inputs, weights), state

  File [...]/trax/layers/base.py, line 582, in _forward
    raw_output = raw_fn(x, weights=weights, **self._kwargs)  # pylint: disable=protected-access

  File [...]/trax/layers/metrics.py, line 100, in _Accuracy
    return np.equal(predicted_category, target_category).astype(np.float32)

  File [...]/jax/numpy/lax_numpy.py, line 422, in <lambda>
    fn = lambda x1, x2: lax_fn(*_promote_args(numpy_fn.__name__, x1, x2))

  File [...]/jax/lax/lax.py, line 333, in eq
    return eq_p.bind(x, y)

  File [...]/site-packages/jax/core.py, line 202, in bind
    out_tracer = top_trace.process_primitive(self, tracers, kwargs)

  File [...]/jax/interpreters/partial_eval.py, line 142, in process_primitive
    return self.default_process_primitive(primitive, tracers, params)

  File [...]/jax/interpreters/partial_eval.py, line 152, in default_process_primitive
    out_aval = primitive.abstract_eval(*avals, **params)

  File [...]/jax/lax/lax.py, line 1710, in standard_abstract_eval
    return ShapedArray(shape_rule(*args, **kwargs), dtype_rule(*args, **kwargs))

  File [...]/jax/lax/lax.py, line 1767, in _broadcasting_shape_rule
    raise TypeError(msg.format(name, ', '.join(map(str, map(tuple, shapes)))))

TypeError: eq got incompatible shapes for broadcasting: (1, 200), (1, 3000).
...
```

**Comment by DevKretov** [comment]
The problem you face is by no means connected to the lengths of the input-target pairs. I train Reformer model on summarisation task, my inputs have length 128 tokens and my targets are padded to 64 tokens.

**Comment by tomweingarten** [comment]
I believe it is connected to the length of the input-target pairs, but you gave me an idea :) Based on your input size I set my source to be always 300 and my target to always be a multiple of 300. Now it's working great. I haven't had time yet to figure out why this is.

**Comment by tomweingarten** [comment]
Spoke too soon, turns out setting the target to always be a multiple of the input doesn't work (I had a hack elsewhere in my code that was masking the bug, when removed it starts crashing again).

After digging deeper, I believe the problem is that Reformer is outputting the encoder output in addition to the decoder output. It looks like this bug may already be fixed in master, but I can't verify because tensorflow-text is not installable yet on Ubuntu 20.04, and it is now a hard requirement for trax Inputs. I will verify when that issue is resolved and I can run the new version.

**Comment by Enumaris** [comment]
Given the Q=K requirement for this implementation of LSH-attention, how does encoder-decoder attention even work mathematically?

**Comment by tomweingarten** [comment]
I've tested this on master and it's resolved.
