### ISSUE TITLE
slicing mask tensor results in type error during backward pass

### ISSUE THREAD

**Issue by py4** [google/trax#581]
[Here](https://github.com/google/trax/blob/482c794a0e5a08960af82e74f8ca7f849583b58f/trax/models/reformer/reformer.py#L923) is your serial layer for the full reformer model:
```
  return tl.Serial(
      # Input: encoder_side_tokens, decoder_side_tokens
      # Copy decoder tokens for use in loss.
      tl.Select([0, 1, 1]),                 # tok_e tok_d tok_d
      tl.Branch([], [tl.PaddingMask(),
                     tl.Fn('Squeeze',
                           lambda x: np.squeeze(x, (1, 2)), n_out=1)]),
      #                                     # tok_e mask  tok_d .....

      # Encode.
      encoder,                              # vec_e  mask tok_d .....

      # Decode.
      tl.Select([2, 0, 1]),                 # tok_d vec_e mask .....
      tl.ShiftRight(mode=mode),             # tok_d vec_e mask .....
      out_encoder,                          # vec_d vec_e mask .....
      tl.Dup(),                             # vec_d1 vec_d2 vec_e mask .....
      tl.ReversibleSerial(encoder_decoder_blocks),
      tl.Fn('XYAvg',
            lambda x, y: (x + y) / 2.0),    # vec_d vec_e mask .....
      tl.LayerNorm(),                       # vec_d vec_e mask .....

      # Map to output vocab.
      tl.Select([0], n_in=3),               # vec_d .....
      tl.Dense(output_vocab_size),          # vec_d .....
      tl.LogSoftmax(),                      # vec_d .....
  )
```

Now in my example, the input size is 64. If i add a slicing layer to slice mask before decoder:
```
  return tl.Serial(
      # Input: encoder_side_tokens, decoder_side_tokens
      # Copy decoder tokens for use in loss.
      tl.Select([0, 1, 1]),                 # tok_e tok_d tok_d
      tl.Branch([], [tl.PaddingMask(),
                     tl.Fn('Squeeze',
                           lambda x: np.squeeze(x, (1, 2)), n_out=1)]),
      #                                     # tok_e mask  tok_d .....

      # Encode.
      encoder,                              # vec_e  mask tok_d .....
      tl.Fn(lambda x,y: (x, y[:,:64])), # vec_e mask_64 tok_d
      # Decode.
      tl.Select([2, 0, 1]),                 # tok_d vec_e mask .....
      tl.ShiftRight(mode=mode),             # tok_d vec_e mask .....
      out_encoder,                          # vec_d vec_e mask .....
      tl.Dup(),                             # vec_d1 vec_d2 vec_e mask .....
      tl.ReversibleSerial(encoder_decoder_blocks),
      tl.Fn('XYAvg',
            lambda x, y: (x + y) / 2.0),    # vec_d vec_e mask .....
      tl.LayerNorm(),                       # vec_d vec_e mask .....

      # Map to output vocab.
      tl.Select([0], n_in=3),               # vec_d .....
      tl.Dense(output_vocab_size),          # vec_d .....
      tl.LogSoftmax(),                      # vec_d .....
  )
```

I get this stack trace: 
```
Traceback (most recent call last):
  File "train_reformer.py", line 280, in <module>
    train_main(learning_curve=args.learning_curve, inference=args.inference, checkpoint_name=args.checkpoint_name)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/gin/config.py", line 1078, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/gin/config.py", line 1055, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "train_reformer.py", line 254, in train_main
    trainer.train_epoch(n_steps=step_size, n_eval_steps=n_eval_steps)
  File "/home/pooya/seq2seq/Reformer/tensorflow/trax/supervised/trainer_lib.py", line 327, in train_epoch
    self.train_step(batch)
  File "/home/pooya/seq2seq/Reformer/tensorflow/trax/supervised/trainer_lib.py", line 374, in train_step
    self._step, opt_state, batch, self._model_state, self._rngs)
  File "/home/pooya/seq2seq/Reformer/tensorflow/trax/supervised/trainer_lib.py", line 777, in update
    return mapped_update(np.repeat(i, n_devices), opt_state, batch, state, rng)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/api.py", line 932, in f_pmapped
    name=flat_fun.__name__)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/core.py", line 895, in call_bind
    outs = primitive.impl(f, *args, **params)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/interpreters/pxla.py", line 406, in xla_pmap_impl
    global_axis_size, devices, name, *abstract_args)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/linear_util.py", line 220, in memoized_fun
    ans = call(fun, *args)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/interpreters/pxla.py", line 462, in parallel_callable
    dynamic_fun, [pval] + pvals, instantiate=False, stage_out_calls=True, bottom=True)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/interpreters/partial_eval.py", line 358, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/linear_util.py", line 149, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/interpreters/pxla.py", line 455, in dynamic_fun
    return fun.call_wrapped(*args)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/linear_util.py", line 149, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/pooya/seq2seq/Reformer/tensorflow/trax/supervised/trainer_lib.py", line 766, in mapped_update
    grads, state = grad_fn(weights, batch, state, rng)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/api.py", line 367, in grad_f_aux
    (_, aux), g = value_and_grad_f(*args, **kwargs)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/api.py", line 428, in value_and_grad_f
    g = vjp_py(onp.ones((), dtype=dtype))
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/api.py", line 1283, in _vjp_pullback_wrapper
    ans = fun(*args)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/interpreters/ad.py", line 113, in vjp_
    arg_cts = backward_pass(jaxpr, consts, dummy_args, dummy_primals_and_cts)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/interpreters/ad.py", line 207, in backward_pass
    cts_out = get_primitive_transpose(eqn.primitive)(cts_in, *invals, **eqn.params)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/lax/lax.py", line 3097, in _gather_transpose_rule
    return [scatter_add(zeros, start_indices, t, scatter_dnums), ad_util.zero]
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/lax/lax.py", line 766, in scatter_add
    jaxpr, consts = _reduction_jaxpr(add, _abstractify(_const(operand, 0)))
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/lax/lax.py", line 898, in _reduction_jaxpr
    jaxpr, _, consts = pe.trace_to_jaxpr(comp, (pval, pval), instantiate=False)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/interpreters/partial_eval.py", line 358, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/linear_util.py", line 149, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/lax/lax.py", line 897, in <lambda>
    comp = lu.wrap_init(lambda x, y: (computation(x, y),))
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/lax/lax.py", line 280, in add
    return add_p.bind(x, y)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/core.py", line 202, in bind
    out_tracer = top_trace.process_primitive(self, tracers, kwargs)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/interpreters/partial_eval.py", line 99, in process_primitive
    return self.default_process_primitive(primitive, tracers, params)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/interpreters/partial_eval.py", line 107, in default_process_primitive
    out_aval = primitive.abstract_eval(*avals, **params)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/lax/lax.py", line 1539, in standard_abstract_eval
    return ShapedArray(shape_rule(*args, **kwargs), dtype_rule(*args, **kwargs))
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/lax/lax.py", line 1579, in naryop_dtype_rule
    raise TypeError(msg.format(name, typename, i, i, typenames))
TypeError: add does not accept dtype bool at position 0. Accepted dtypes at position 0 are subtypes of complexfloating, integer, floating.
```

Where does this add operation is coming from for this bool type which is obviously related to the sliced mask? 

And by the way if i return a new value instead of the sliced mask like this:
```
  return tl.Serial(
      # Input: encoder_side_tokens, decoder_side_tokens
      # Copy decoder tokens for use in loss.
      tl.Select([0, 1, 1]),                 # tok_e tok_d tok_d
      tl.Branch([], [tl.PaddingMask(),
                     tl.Fn('Squeeze',
                           lambda x: np.squeeze(x, (1, 2)), n_out=1)]),
      #                                     # tok_e mask  tok_d .....

      # Encode.
      encoder,                              # vec_e  mask tok_d .....
     tl.Fn(lambda x,y: (x, jax.lax.full((x.shape[0], x.shape[1]), True, dtype=bool))), # vec_e mask_64 tok_d
      # Decode.
      tl.Select([2, 0, 1]),                 # tok_d vec_e mask .....
      tl.ShiftRight(mode=mode),             # tok_d vec_e mask .....
      out_encoder,                          # vec_d vec_e mask .....
      tl.Dup(),                             # vec_d1 vec_d2 vec_e mask .....
      tl.ReversibleSerial(encoder_decoder_blocks),
      tl.Fn('XYAvg',
            lambda x, y: (x + y) / 2.0),    # vec_d vec_e mask .....
      tl.LayerNorm(),                       # vec_d vec_e mask .....

      # Map to output vocab.
      tl.Select([0], n_in=3),               # vec_d .....
      tl.Dense(output_vocab_size),          # vec_d .....
      tl.LogSoftmax(),                      # vec_d .....
  )
```

I reach to this supposedly unreachable error:

```
    train_main(learning_curve=args.learning_curve, inference=args.inference, checkpoint_name=args.checkpoint_name)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/gin/config.py", line 1078, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/gin/config.py", line 1055, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "train_reformer.py", line 246, in train_main
    save_every=save_every)
  File "/home/pooya/seq2seq/Reformer/tensorflow/trax/supervised/trainer_lib.py", line 222, in __init__
    self.reset(output_dir, init_checkpoint=init_checkpoint)
  File "/home/pooya/seq2seq/Reformer/tensorflow/trax/supervised/trainer_lib.py", line 306, in reset
    opt_state, model_state = self._new_opt_state_and_model_state()
  File "/home/pooya/seq2seq/Reformer/tensorflow/trax/supervised/trainer_lib.py", line 177, in <lambda>
    model_target_shape, self._inputs.target_dtype, init_rng))
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/api.py", line 150, in f_jitted
    name=flat_fun.__name__)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/core.py", line 895, in call_bind
    outs = primitive.impl(f, *args, **params)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/interpreters/xla.py", line 457, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, *map(arg_spec, args))
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/linear_util.py", line 220, in memoized_fun
    ans = call(fun, *args)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/interpreters/xla.py", line 474, in _xla_callable
    fun, pvals, instantiate=False, stage_out_calls=True, bottom=True)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/interpreters/partial_eval.py", line 358, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/home/pooya/my_envs/reformer/lib/python3.6/site-packages/jax/linear_util.py", line 149, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/pooya/seq2seq/Reformer/tensorflow/trax/supervised/trainer_lib.py", line 166, in new_opt_state_and_model_state
    weights, state = m.init(input_signature)
  File "/home/pooya/seq2seq/Reformer/tensorflow/trax/layers/base.py", line 321, in init
    input_signature, trace)
trax.layers.base.LayerError: Exception passing through layer Serial (in init):
  layer created in file [...]/trax/supervised/trainer_lib.py, line 164
  layer input shapes: (ShapeDtype{shape:(1, 64), dtype:int32}, ShapeDtype{shape:(1, 1024), dtype:int64}, ShapeDtype{shape:(1, 1024), dtype:<class 'jax.numpy.lax_numpy.float32'>})

  File [...]/trax/layers/combinators.py, line 91, in new_weights_and_state
    outputs, _ = sublayer._forward_abstract(inputs)

LayerError: Exception passing through layer Serial (in _forward_abstract):
  layer created in file [...]/models/reformer/reformer.py, line 1285
  layer input shapes: (ShapeDtype{shape:(1, 64), dtype:int32}, ShapeDtype{shape:(1, 1024), dtype:int64})

  File [...]/trax/math/jax.py, line 175, in shape_fun
    jax_shapes = jax.eval_shape(f, *args, **kwargs)

  File [...]/site-packages/jax/api.py, line 2104, in eval_shape
    *map(abstractify, args_flat))

  File [...]/jax/interpreters/partial_eval.py, line 274, in abstract_eval_fun
    instantiate=True)

  File [...]/jax/interpreters/partial_eval.py, line 358, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)

  File [...]/site-packages/jax/linear_util.py, line 149, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))

  File [...]/site-packages/jax/linear_util.py, line 149, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))

  File [...]/trax/layers/base.py, line 477, in call_on_input
    return self.forward_with_state(x, weights=weights, state=state, rng=rng)

  File [...]/trax/layers/combinators.py, line 76, in forward_with_state
    outputs, s = layer.pure_fn(inputs, w, s, rng)

LayerError: Exception passing through layer ReversibleSerial (in pure_fn):
  layer created in file [...]/models/reformer/reformer.py, line 1278
  layer input shapes: (ShapeDtype{shape:(1, 1024, 512), dtype:float32}, ShapeDtype{shape:(1, 1024, 512), dtype:float32}, ShapeDtype{shape:(1, 64, 512), dtype:float32}, ShapeDtype{shape:(1, 64), dtype:bool})

  File [...]/trax/layers/base.py, line 562, in _do_custom_gradients
    output, state = _do_forward(x, weights)

  File [...]/site-packages/jax/api.py, line 1503, in __call__
    num_consts=len(consts))

  File [...]/site-packages/jax/core.py, line 202, in bind
    out_tracer = top_trace.process_primitive(self, tracers, kwargs)

  File [...]/jax/interpreters/partial_eval.py, line 99, in process_primitive
    return self.default_process_primitive(primitive, tracers, params)

  File [...]/jax/interpreters/partial_eval.py, line 107, in default_process_primitive
    out_aval = primitive.abstract_eval(*avals, **params)

  File [...]/site-packages/jax/api.py, line 1566, in fun_abstract_eval
    return pe.abstract_eval_fun(fun_impl, *avals, **params)

  File [...]/jax/interpreters/partial_eval.py, line 274, in abstract_eval_fun
    instantiate=True)

  File [...]/jax/interpreters/partial_eval.py, line 358, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)

  File [...]/site-packages/jax/linear_util.py, line 149, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))

  File [...]/site-packages/jax/api.py, line 1554, in fun_impl
    return core.eval_jaxpr(params['jaxpr'], consts, *args)

  File [...]/site-packages/jax/core.py, line 269, in eval_jaxpr
    ans = eqn.primitive.bind(*(subfuns + in_vals), **params)

  File [...]/site-packages/jax/core.py, line 202, in bind
    out_tracer = top_trace.process_primitive(self, tracers, kwargs)

  File [...]/jax/interpreters/partial_eval.py, line 99, in process_primitive
    return self.default_process_primitive(primitive, tracers, params)

  File [...]/jax/interpreters/partial_eval.py, line 107, in default_process_primitive
    out_aval = primitive.abstract_eval(*avals, **params)

  File [...]/site-packages/jax/api.py, line 1566, in fun_abstract_eval
    return pe.abstract_eval_fun(fun_impl, *avals, **params)

  File [...]/jax/interpreters/partial_eval.py, line 274, in abstract_eval_fun
    instantiate=True)

  File [...]/jax/interpreters/partial_eval.py, line 358, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)

  File [...]/site-packages/jax/linear_util.py, line 149, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))

  File [...]/site-packages/jax/api.py, line 1554, in fun_impl
    return core.eval_jaxpr(params['jaxpr'], consts, *args)

  File [...]/site-packages/jax/core.py, line 269, in eval_jaxpr
    ans = eqn.primitive.bind(*(subfuns + in_vals), **params)

  File [...]/site-packages/jax/core.py, line 202, in bind
    out_tracer = top_trace.process_primitive(self, tracers, kwargs)

  File [...]/jax/interpreters/partial_eval.py, line 99, in process_primitive
    return self.default_process_primitive(primitive, tracers, params)

  File [...]/jax/interpreters/partial_eval.py, line 107, in default_process_primitive
    out_aval = primitive.abstract_eval(*avals, **params)

  File [...]/site-packages/jax/api.py, line 1566, in fun_abstract_eval
    return pe.abstract_eval_fun(fun_impl, *avals, **params)

  File [...]/jax/interpreters/partial_eval.py, line 274, in abstract_eval_fun
    instantiate=True)

  File [...]/jax/interpreters/partial_eval.py, line 358, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)

  File [...]/site-packages/jax/linear_util.py, line 149, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))

  File [...]/site-packages/jax/api.py, line 1554, in fun_impl
    return core.eval_jaxpr(params['jaxpr'], consts, *args)

  File [...]/site-packages/jax/core.py, line 269, in eval_jaxpr
    ans = eqn.primitive.bind(*(subfuns + in_vals), **params)

  File [...]/site-packages/jax/core.py, line 202, in bind
    out_tracer = top_trace.process_primitive(self, tracers, kwargs)

  File [...]/jax/interpreters/partial_eval.py, line 99, in process_primitive
    return self.default_process_primitive(primitive, tracers, params)

  File [...]/jax/interpreters/partial_eval.py, line 107, in default_process_primitive
    out_aval = primitive.abstract_eval(*avals, **params)

  File [...]/jax/lax/lax.py, line 1536, in standard_abstract_eval
    assert pe._thread_local_state.remat, msg

AssertionError: If you see this error, please let us know by opening an issue at
https://github.com/google/jax/issues

since we thought this was unreachable!
  In call to configurable 'train_main' (<function train_main at 0x7fbb9eea8158>)
```

Can you explain what is wrong here?
tnx

**Comment by lukaszkaiser** [comment]
Sorry to say, I tried a little bit and this was not debuggable to me. We've improved though, as Reformer on head now uses the cleaner ReversibleSerialV2 code, which hopefully will be easier to resolve. Could you try again on head and let us know if the error persists?
