### ISSUE TITLE
Import error: Cannot find parameter "kwargs" 

### ISSUE THREAD

**Issue by tomweingarten** [google/trax#747]
### Description

trax was working great for me a month ago, but now I can no longer import it due to this error. Any help would be greatly appreciated, thank you!

### Environment information

```
OS:  Ubuntu 20.04

$ pip freeze | grep tensor
mesh-tensorflow==0.1.13
tensor2tensor==1.15.5
tensorboard==2.2.1
tensorboard-plugin-wit==1.6.0.post3
tensorflow==2.2.0
tensorflow-datasets==3.1.0
tensorflow-estimator==2.2.0
tensorflow-gan==2.0.0
tensorflow-gpu==2.2.0
tensorflow-hub==0.8.0
tensorflow-metadata==0.21.2
tensorflow-probability==0.7.0
tensorflow-text==2.2.1

$ pip freeze | grep jax
jax==0.1.65
jaxlib==0.1.45

$ python -V
Python 3.8.2
```

### For bugs: reproduction and error logs

```
# Steps to reproduce:
import trax 
```

```
# Error logs:
Traceback (most recent call last):
  File "/home/tom/.local/lib/python3.8/site-packages/trax/tf_numpy/numpy/__init__.py", line 27, in <module>
    from tensorflow.python.ops.numpy_ops import *
ModuleNotFoundError: No module named 'tensorflow.python.ops.numpy_ops'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tf_nfl_reformer.py", line 3, in <module>
    import trax
  File "/home/tom/.local/lib/python3.8/site-packages/trax/__init__.py", line 18, in <module>
    from trax import layers
  File "/home/tom/.local/lib/python3.8/site-packages/trax/layers/__init__.py", line 23, in <module>
    from trax.layers.activation_fns import *
  File "/home/tom/.local/lib/python3.8/site-packages/trax/layers/activation_fns.py", line 26, in <module>
    from trax import math
  File "/home/tom/.local/lib/python3.8/site-packages/trax/math/__init__.py", line 20, in <module>
    from trax.math import tf as tf_math
  File "/home/tom/.local/lib/python3.8/site-packages/trax/math/tf.py", line 26, in <module>
    from trax.tf_numpy import extensions as tf_np_extensions
  File "/home/tom/.local/lib/python3.8/site-packages/trax/tf_numpy/extensions/__init__.py", line 23, in <module>
    from trax.tf_numpy.extensions.extensions import *
  File "/home/tom/.local/lib/python3.8/site-packages/trax/tf_numpy/extensions/extensions.py", line 30, in <module>
    import trax.tf_numpy.numpy as tf_np
  File "/home/tom/.local/lib/python3.8/site-packages/trax/tf_numpy/numpy/__init__.py", line 39, in <module>
    from trax.tf_numpy.numpy_impl.math_ops import *
  File "/home/tom/.local/lib/python3.8/site-packages/trax/tf_numpy/numpy_impl/math_ops.py", line 1126, in <module>
    def meshgrid(*xi, **kwargs):
  File "/home/tom/.local/lib/python3.8/site-packages/trax/tf_numpy/numpy_impl/utils.py", line 217, in decorator
    raise TypeError('Cannot find parameter "%s" in the numpy function\'s '
TypeError: Cannot find parameter "kwargs" in the numpy function's signature
```

**Comment by lukaszkaiser** [comment]
Thanks for reporting! tf-numpy is/was a part of Trax, but is moving officially to TF 2.3 (to be released soon) and this is causing the problem. We'll work to resolve, I think we simply should not try to import from TF ops when not on nightly.

**Comment by tomweingarten** [comment]
Thanks Lukasz! Your recent commit resolved the issue.
